name: Automatic Server Pull Request
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Run Pull
    environment: Test_Environment
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo ${{ secrets.SSH_PUBLIC_KEY }} > ~/.ssh/known_hosts
    - name: Connect and Pull
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
        cd ${{ secrets.WORK_DIR }}
        git checkout ${{ secrets.MAIN_BRANCH }}
        git pull
        exit
    - name: cleanup
      run: rm -rf ~/.ssh
