name: Automatic Server Pull Request
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Run Pull
    runs-on: ubuntu-latest
    steps:
    - name: Cleanup
      run: echo ${{ secrets.SSH_HOST }}
