name: Automatic Server Pull Request
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Run Pull
    environment: Test_Environment
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH Client
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
    - name: Setup Cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        echo -e "Host ssh.suzuqui.live\nProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" > ~/.ssh/config
    - name: Connect and Pull
      run: |
        ssh -vvv -i ~/.ssh/id_rsa vandre@ssh.suzuqui.live
        cd ${{ secrets.WORK_DIR }}
        git checkout ${{ secrets.MAIN_BRANCH }}
        git pull
        exit
    - name: Cleanup
      run: rm -rf ~/.ssh
